name: Historyland
version: '${project.version}'
main: fr.thejordan.historyland.Historyland
api-version: 1.17
authors: [ TheJordan ]
depend: [Essentials, WorldGuard]
description: Plugin pour HistoryLand
commands:
  armorstandcommand:
    aliases: [ asc ]
  chest:
  collectibles:
  properties:
  hbroadcast:
  hchat:
  hreload:
  visibility:
  hwarps:
  jet:
    aliases: [hrl]
  language:
  light:
    aliases: [lgt]
  motd:
  preferences:
    aliases: [prefs]
  realtime:
  resourcepack:
  rideop:
  shop:
  sit:
  tpr:
